name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      PROJECT: './Scr/StateButton/Breadcrumb.csproj'
      NET6_VERSION: 6.0.400

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: $NET6_VERSION
        
    - name: Install MAUI Workloads
      run: dotnet workload install maui --ignore-failed-sources
        
    - name: Restore dependencies
      run: dotnet restore $PROJECT
      
    - name: Build
      run: dotnet build $PROJECT --configuration $BUILD_CONFIG --no-restore
      
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/
